### ISSUE TITLE
Скрыты пользователи канала

### ISSUE THREAD

**Issue by sigorilla** [shri-2015-org/shriek#101]
Левый список идентичный главному списку пользователей, поэтому отображается только 3 первых пользователя, остальных не видно.

**Comment by ghost** [comment]
потому что используются одинаковые классы для обоих списков и для правой и для левой.
А на левой панельке у нас стоит ограничение по высоте до трех человек, поэтому такая билибарда получилось.
Сейчас исправлю!

**Comment by sigorilla** [comment]
Да, я понимаю из-за чего это произошло. Просто обнаружил и поэтому написал.

**Comment by ghost** [comment]
Ага, спасибо!
