### ISSUE TITLE
Перемешивание сообщений

### ISSUE THREAD

**Issue by sigorilla** [shri-2015-org/shriek#43]
Сообщения приходят в канал, где ты сейчас сидишь. При этом сообщения могут отправляться с другого канала.

**Comment by AndrewUldin** [comment]
Как это воспроизвести?

**Comment by sigorilla** [comment]
Создаешь две вкладки в браузере, в каждой вкладке должны быть активны разные каналы. Пишишь в один, а в другой вкладке придет в другой канал. 

Однако если сменишь канал, то все станет нормально.

**Comment by AndrewUldin** [comment]
понятно. щас попробую

**Comment by AndrewUldin** [comment]
https://github.com/shri-2015-org/shriek/pull/47
