### ISSUE TITLE
Загрузка первые сообщения

### ISSUE THREAD

**Issue by sigorilla** [shri-2015-org/shriek#44]
@amelice говорила, что при загрузке чата появляются первые сообщения вместо последних.

Я не смог воспроизвести его, либо не понял сути. @amelice, можешь сказать как это у тебя произошло?

**Comment by AndrewUldin** [comment]
тебе нужно иметь больше 100 сообщений чтобы это словить. но вообще, я пока что убрал оттуда лимит, не знаю пока что с этим делать. когда появляется лимит, все ломается. пусть ишью висит пока что.

**Comment by ghost** [comment]
Извините, только увидела это ишью (
Было такое раньше, грузились какой-то лимит первых сообщений. Потом стало как нужно, я сегодня еще раз почистила сообщений в базе и забила больше 150 сообщений, чтоб удостовериться, что правильно работает.  Все хорошо.

**Comment by sigorilla** [comment]
Fixed
