### ISSUE TITLE
Форма логина при входе

### ISSUE THREAD

**Issue by sigorilla** [shri-2015-org/shriek#46]
Немного ломается форма входа при выводе ошибок.
![image](https://cloud.githubusercontent.com/assets/1208639/9980754/0eb8d344-5fad-11e5-8cc1-91cba1d13de6.png)

**Comment by TehZarathustra** [comment]
Починил

**Comment by sigorilla** [comment]
На будущее в сообщении к комиту можно (и нужно) писать `fix #NN`, где `NN` - номер issue или pr. Так он автоматически закроется и при этом будет известно каким комитом его закрыли.

**Comment by TehZarathustra** [comment]
хорошо, спасибо. впредь буду так делать

**Comment by sigorilla** [comment]
Вот еще информация на эту тему: https://help.github.com/articles/closing-issues-via-commit-messages/
