### ISSUE TITLE
Выход пользователя

### ISSUE THREAD

**Issue by sigorilla** [shri-2015-org/shriek#48]
@TehZarathustra 
# Bug report
## Commit

cbccc6c80f36679f6213d3486b6ef6d4bf2a022d
## Как воспроизвести
1. Входим
2. Выходим
3. Снова входим, но оставляем поля пустыми
4. ...
5. Bug!

Итого сохраняется предыдущиЙ пользователь

P.S. Чтобы такого не было, лучше создавать [PR](https://github.com/shri-2015-org/shriek/compare).

**Comment by TehZarathustra** [comment]
fixed in e25d806528508054ee168654ddef677f52c9ead8
