### ISSUE TITLE
Скрыть список пользователей

### ISSUE THREAD

**Issue by sigorilla** [shri-2015-org/shriek#58]
Работает все ок, но мне кажется, что с точки зреня удобства, распологать `Скрыть` снизу списка пользователей, не рационально. Лучше если бы эта надпись была всегда зафиксирована. Ведь если я раскрыл большой список, то чтобы его обратно скрыть, мне надо проскроллить в самый низ. 

Предлагаю, обсудить это.

**Comment by ghost** [comment]
Вообще поддерживаю.
Но момент, если зафиксировать надпись вверху, то опять же нужно будет вернуться назад, чтобы скрыть.
Может сделаем его плавающим? Будет ездить по мере того как мы скроллим по списку, всегда сбоку.
Типа так
![22](https://cloud.githubusercontent.com/assets/4211776/10173549/79ff767a-66ed-11e5-8420-18b005259e63.png)

**Comment by sigorilla** [comment]
А что если раскрывать список при нажатии на `Каналы` (`Пользователи`), а скролл появляется только где сам список каналов (пользователей), то есть не все боковое меню двигается, а только необходимый список.

**Comment by ghost** [comment]
Помню, вначале такой вариант предалагал еще Вова.
На мой взгляд это не решит проблему скролла на боковом меню. 
1. Допустим у нас `Каналы/Пользователи` будут видны в блоке фиксированной высоты при клике на их хедеры. И мы зафиксировали высоту этих блоков так, чтобы оба в открытом виде не превышали высоту экрана, то есть не создавалось общий скролл на боковом меню. Но вдруг пользователь еще уменьшит экран, то тогда опять же появится общий скролл к имеющимся. То есть три скролла.
2. Потом нужно будет тянуть библиотеку для кастомного скролла для этих блоков, так как в фф, ие стандартные скроллы смотрятся ужасно.

**Comment by sigorilla** [comment]
1. Ну тут должны вступать `@media` условия. Мы так и будем показывать на мобильном устройстве чат? Надо ведь и для маленьких экранов сделать. Следовательно надо продумать стили для низких разрешений.
2. У нас сейчас присутствует как минимум всегда один скролл, и иногда будут еще два скролла. Разве они уже не выглядят ужастно в фф?

**Comment by ghost** [comment]
сейчас один скролл, он выглядит ужасно в фф, представь будет таких еще два ) и все это на левой панельки одновременно

**Comment by ghost** [comment]
по поводу мобильной версии, разве мы рассматривали такой вариант? Если так, то наверно нужно решить, как вообще должно перестраиваться чат.

**Comment by bibimij** [comment]
Чем плоха кнопка «Скрыть»? Мы же не делаем продукт-миллионник. Пролистать список из 20 элементов не сложно. Фиксировать тоже не надо, потому что придётся опять переделывать то, что я ещё не доделал. =\ 
Чем плох скролл всего сайдбара? Да ничем. Почему плохо скроллировать пользователей и группы отдельно? Потому что получится маленькая неудобная «амбразура» или же придётся писать логику разворачивания блока чтобы было видно → опять появится скролл.
Давайте оставим как есть, но добавить маленькое улучшение. При разворачивании блока подписываемся на событие mouseleave, в котором прописан setTimeout секунд на 10. Функция для таймера будет содержать клик по «Свернуть». Просто, как дверь.

**Comment by ghost** [comment]
А я не понимаю смысла сетТаймаут.  Думаю это лишнее, я бы не хотела как пользователь за меня - без моего ведомо скрыли список. Например, я развернула список каналов специально, а мне закрывают принудительно. Кнопка "Cкрыть" мне достаточно.

**Comment by bibimij** [comment]
@amelice логика в том, что если за 10 секунд курсор не вернулся обратно, пользователю уже не нужен весь список и его можно скрыть. Тут, правда, есть один нюанс — мобильная версия. В ней нет курсора.
Однако суть топика — решить судьбу кнопки «Скрыть». Автоматическое схлопывание — как способ оставить вёрстку без изменений, но в то же время сэкономить место. :)

**Comment by ghost** [comment]
Не хочу показаться занудой, но все же, если я специльно разворачиваю список и не закрываю его обратно, то наверно есть необходимость в этом для меня. :)
