### ISSUE TITLE
Окно добавление канала

### ISSUE THREAD

**Issue by ghost** [shri-2015-org/shriek#60]
Если у одного пользователя открыто окно, а другой в это время создает у себя новое, то при добавлении первым канала, у второго автоматом закрывается окно

**Comment by sigorilla** [comment]
Ошибка всего скорее [в этой строке](https://github.com/shri-2015-org/shriek/blob/develop/app/stores/ChannelsStore.js#L8). Потому что когда приходят данные, state обновляется и `show_modal` становиться `false`. 

Как лечить не знаю

**Comment by ghost** [comment]
Ага, оказалось дело в том, что мы ж устанавливаем стейты через стор, и если стейты меняем во вьюхе, то стору фиолетово. Поэтому получается, вьюха рендерится когда в стор обработчики срабатывают, и со стейтами в стор. Пофиксила, чуть позже выкачу.

**Comment by ghost** [comment]
То есть нужно обработчики вешать только через экшн и оттудого передать новые значения для стейтов в стор.

**Comment by sigorilla** [comment]
Выкати реквестом.
