### ISSUE TITLE
Обработка сообщений

### ISSUE THREAD

**Issue by sigorilla** [shri-2015-org/shriek#65]
Какие из фич Markdown нам не нужны?

Предлагаю убрать:
- Заголовки с 1 по 3 уровень
- Картинки
- Ссылки (вида: `(text)[url]`)
  - Вместо этого можно будет парсить ссылки на OpenGraph
  - Если же ссылка не парсится, но является каким-нибудь файлом, то можно вкладывать во вложение к сообщению

Ваши предложения :smile:

**Comment by bibimij** [comment]
Оставь только форматирование (bold, italic, underline, striked), списки, цитаты и коды. Ссылки должны распознаваться автоматически и прикрепляться в виде карточки, данные для которой берутся из OG.

**Comment by sigorilla** [comment]
Close in sigorilla/shriek-markdown@b4e649d863068351cc38e06489baf790eba7e6a4
