### ISSUE TITLE
user.salt

### ISSUE THREAD

**Issue by bibimij** [shri-2015-org/shriek#70]
В объекте пользователя, который бродкастится, фигурирует элемент salt. Нехорошо.

**Comment by bibimij** [comment]
password тоже убрать.

**Comment by sigorilla** [comment]
@TehZarathustra вроде использует `hashedPassword` при логине через сервисы. Именно для этого было добавлено [это](https://github.com/shri-2015-org/shriek/blob/develop/app/models/user.js#L84). Но это надо фиксить...

**Comment by TehZarathustra** [comment]
Не совсем верно, я его использую в сессии (уже локалсторадж), чтобы автологинить

**Comment by sigorilla** [comment]
Если тебе не присылать его, то автологин будет ломаться. Правильно?

**Comment by bibimij** [comment]
Ок. Но соль всё равно хранить нехорошо. :)06.10.2015, 00:09, "Igor Stepanov" notifications@github.com:Если тебе не присылать его, то автологин будет ломаться. Правильно?

**Comment by TehZarathustra** [comment]
Соль хранить не надо, да. Но в hashedPassword'е ничего плохого не вижу, или это большая проблема? Если убрать, то ничего не сломается, кроме автологина.

**Comment by bibimij** [comment]
Не очень большая проблема. Но как-то странно хранить на клиенте пароль для проверки. Это значит, что мы сверяемся с паролем на сервере, а значит можно его взять и подменить.06.10.2015, 00:11, "TehZarathustra" notifications@github.com:Соль хранить не надо, да. Но в hashedPassword'е ничего плохого не вижу, или это большая проблема?

**Comment by sigorilla** [comment]
Да честно говоря, авторизация у нас слабое место. Я посмотрел, как Кантор [советует](https://www.youtube.com/watch?v=A3TUXGI_iuM) это делать. Собственно в socket.io есть для этого возможности, но мы не юзаем их.

**Comment by TehZarathustra** [comment]
Если вытщить этот хэш-пароль и вбить руками в поле ввода, то он не пустит ведь, или если, скажем, передать что-то другое — увидим такой же результат. В целом, конечно, согласен, такой способ, в любом случае, далек от идеального. Переделаю

**Comment by bibimij** [comment]
Проблема несколько иная. Запись о пользователе бродкастится на всех. Таким образом, мы можем скопировать эту запись, записать себе в LocalStorage и писать от чужого имени, менять пароль и т. д.

**Comment by sigorilla** [comment]
Убрал из бродкаста в c422d1ecc9ac84f159b08e5d3931a15e1d61b686
