### ISSUE TITLE
Выход с двух вкладок

### ISSUE THREAD

**Issue by sigorilla** [shri-2015-org/shriek#80]
Открыто две вкладки. Обновляю любую — выходит из обоих вкладок. И чтобы снова войти, надо перезагружать страницу.

Происходит это из-за того, что событие `user leave` вызывается при обновлении страницы и следовательно при нем никнейм соответствует тому, что лежит в localStorage. Следовательно он это удаляет. И появляется окно авторизации.

Есть мысли как починить?

**Comment by bibimij** [comment]
В моём PR #77 я вроде бы порешал эту проблему путём отправки броадкастом события `user disconnected` вместо `user leave`. Попробуй проверить на свежем девелопе.
