### ISSUE TITLE
Дата сообщения при отправке

### ISSUE THREAD

**Issue by sigorilla** [shri-2015-org/shriek#90]
Сейчас дата сообщения проставляется только в событии `channel get`. Однако этого не происходит при событии `message send`.

**Comment by sigorilla** [comment]
Предлагаю вынести это в метод модели message. То есть использовать для этого mongoose.

**Comment by sigorilla** [comment]
Кроме того, если чат открыт довольно долго и наступает ночь, то дата останется старой, следовательно надо как-то обновить дату у все сообщений. Может сделать только время, но при наведении показывает дату.

И кто-то хотел перенести дату/время справа налево.

**Comment by bibimij** [comment]
Может проводить черту между датами, как в slack?
