### ISSUE TITLE
Ошибка на ноде при создании чата

### ISSUE THREAD

**Issue by ghost** [shri-2015-org/shriek#94]
При любом создании чата, в консоли где запущена нода, выводится ошибка. При этом сам канал создается удачно.
Я не смогла понять почему так происходит, посмотрите пожалуйста.

**Comment by sigorilla** [comment]
Проблему локализовал до `addNewChannel` в `ChannelsStore`. Она вызывается два раза.
Я прошел весь стек вызова `addNewChannel`, но так и не понял, почему ALT после одного диспача последовательно вызывает два раза `addNewChannel`.

Магия — больше нечего сказать. :tophat: :dizzy: :rabbit: :tada: 

Решение можно совместить с #84

**Comment by ghost** [comment]
Игорь, а что значит проблему локализовал?  Это значит ли по твоему дальнейшему повествованию, что нашел в чем причина, но не понимаешь почему так?

**Comment by sigorilla** [comment]
Нет, я лишь понял почему дважды вызывается сокет-событие. А вот почему alt так делает, я не понял.

**Comment by ghost** [comment]
Ты думаешь, ошибка с этим связано?

**Comment by sigorilla** [comment]
Поставь breakpoint на функции, которые создаю новый канал, и посмотри ход сценария. Я лично увидел некоторую магию.

И проблема точно не в ноде.
